---
- name: Run Terraform commands
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Change to directory containing main.tf
      ansible.builtin.command:
        path: "/home/ec2-user/terraform-aws"  # Update this path to the directory containing your main.tf file

    - name: Initialize Terraform
      ansible.builtin.command:
        cmd: terraform init

    - name: Plan Terraform changes
      ansible.builtin.command:
        cmd: terraform plan

    - name: Apply Terraform changes
      ansible.builtin.command:
        cmd: terraform apply -auto-approve
