---
- name: Run Terraform commands
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Initialize Terraform
      command:
        cmd: terraform init
        chdir: "/home/ec2-user/terraform-aws"
      
    - name: Plan Terraform changes
      command:
        cmd: terraform plan
        chdir: "/home/ec2-user/terraform-aws"

    - name: Apply Terraform changes
      command:
        cmd: terraform apply -auto-approve
        chdir: "/home/ec2-user/terraform-aws"
