---
- name: Run Terraform
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone Terraform repository
      git:
        repo: "https://github.com/ansible447karthik/Prosimo.git"
        dest: "/tmp/terraform"
        version: "main"
      register: git_clone

    - name: Run Terraform commands
      shell: |
        cd /tmp/terraform/terraform
        terraform init
        terraform plan
        terraform apply -auto-approve
      when: git_clone.changed
